updates documentation
catbytes-community/webplatform-backend pull request #40
Opened 2024-12-01 11:49 UTC by marinacatbytes

This PR:
- provides step by step instructions how to run project locally
- provides sample .env structure
- provides order of SQL scripts for correct DB setup

2024-12-02 07:41 UTC, yellalena requested changes

2024-12-02 07:41 UTC, yellalena commented on README.md
> +1. Follow `/docs/how-tos/aws_local_db_connection` to install AWS CLI and configure AWS credentials, don't have to connect to AWS RDS database from local machine
AWS access is only needed for remote RDS access. So it's either configuring AWS credentials OR ENVIRONMENT=local + local psql instance

2024-12-02 07:41 UTC, yellalena commented on README.md
> +### How to run project locally
good idea to put it together here ☺️

2024-12-02 11:21 UTC, yellalena commented on README.md
> +Once you are authenticated with AWS CLI and you have the local PostgreSQL setup, you should successfully run `npm start` to start the server
or ? :)

2024-12-10 09:38 UTC, yellalena approved these changes

2024-12-10 09:39 UTC, yellalena approved these changes

2024-12-10 09:47 UTC, yellalena approved these changes

2024-12-10 11:08 UTC, vm2052 submitted a review, later dismissed

2024-12-10 11:09 UTC, vm2052 approved these changes

2024-12-10 20:27 UTC, merged